name: BananoEconomy
version: ${project.version}
main: banano.bananominecraft.bananoeconomy.Main
api-version: 1.16
authors: [Kirby]
description: Hello World
depend: [Vault]
softdepend: [MBedwars]
commands:

  nodeinfo:
    description: Prints node info
    aliases: [node]

  deposit:
    aliases: [dep]
    description: Displays your deposit address

  tip:
    description: Send a tip to another player

  withdraw:
    description: Withdraw BAN to an address

  balance:
    description: Displays your balance
    aliases: [bal]
  
  donate:
    description: Donate to the game wallet
    
  3ne9pcgmg3iuy:
    description: Reward player
    permission: BananoEconomy.rewardplayer
    permission-message: You do not have /<permission>

  freeze:
    aliases: [frz]
    description: freeze player's account
    permission: BananoEconomy.freezer
    permission-message: You do not have /<permission>
    usage: |
      /<command> player - freezes account of player

  unfreeze:
    aliases: [unf]
    description: unfreeze player's account
    permission: BananoEconomy.freezer
    permission-message: You do not have /<permission>
    usage: |
      /<command> player - unfreezes account of player


permissions:
  BananoEconomy.nodeinfo.ip:
      description: This permission allows users to see the node IP with the nodeinfo command
      default: op
  BananoEconomy.nodeinfo:
      description: This permission allows
  BananoEconomy.freezer:
      description: freeze boys
      default: op
  BananoEconomy.rewardplayer:
      description: reward player
      default: op

